/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SouscriptionRouteImport } from './routes/souscription'
import { Route as RejoindreRouteImport } from './routes/rejoindre'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminsRouteImport } from './routes/admins'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SouscriptionIndexRouteImport } from './routes/souscription.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SouscriptionConfirmationRouteImport } from './routes/souscription.confirmation'
import { Route as AppVentesRouteImport } from './routes/app.ventes'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppStockRouteImport } from './routes/app.stock'
import { Route as AppRapportsRouteImport } from './routes/app.rapports'
import { Route as AppProfilRouteImport } from './routes/app.profil'
import { Route as AppProduitsRouteImport } from './routes/app.produits'
import { Route as AppParametresRouteImport } from './routes/app.parametres'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppFournisseursRouteImport } from './routes/app.fournisseurs'
import { Route as AppEquipeRouteImport } from './routes/app.equipe'
import { Route as AppDevisRouteImport } from './routes/app.devis'
import { Route as AppDepensesRouteImport } from './routes/app.depenses'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppCaisseRouteImport } from './routes/app.caisse'
import { Route as AppAbonnementRouteImport } from './routes/app.abonnement'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminFacturationRouteImport } from './routes/admin.facturation'
import { Route as AdminBoutiquesRouteImport } from './routes/admin.boutiques'
import { Route as AdminAbonnementsRouteImport } from './routes/admin.abonnements'
import { Route as AppProduitsIndexRouteImport } from './routes/app.produits.index'
import { Route as AppProduitsNouveauRouteImport } from './routes/app.produits.nouveau'
import { Route as AppProduitsProductIdRouteImport } from './routes/app.produits.$productId'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SouscriptionRoute = SouscriptionRouteImport.update({
  id: '/souscription',
  path: '/souscription',
  getParentRoute: () => rootRouteImport,
} as any)
const RejoindreRoute = RejoindreRouteImport.update({
  id: '/rejoindre',
  path: '/rejoindre',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRoute = AdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SouscriptionIndexRoute = SouscriptionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SouscriptionRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SouscriptionConfirmationRoute =
  SouscriptionConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => SouscriptionRoute,
  } as any)
const AppVentesRoute = AppVentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppRapportsRoute = AppRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppProduitsRoute = AppProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppFournisseursRoute = AppFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppDevisRoute = AppDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => AppRoute,
} as any)
const AppDepensesRoute = AppDepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCaisseRoute = AppCaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => AppRoute,
} as any)
const AppAbonnementRoute = AppAbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => AppRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturationRoute = AdminFacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBoutiquesRoute = AdminBoutiquesRouteImport.update({
  id: '/boutiques',
  path: '/boutiques',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbonnementsRoute = AdminAbonnementsRouteImport.update({
  id: '/abonnements',
  path: '/abonnements',
  getParentRoute: () => AdminRoute,
} as any)
const AppProduitsIndexRoute = AppProduitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProduitsRoute,
} as any)
const AppProduitsNouveauRoute = AppProduitsNouveauRouteImport.update({
  id: '/nouveau',
  path: '/nouveau',
  getParentRoute: () => AppProduitsRoute,
} as any)
const AppProduitsProductIdRoute = AppProduitsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AppProduitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admins': typeof AdminsRoute
  '/app': typeof AppRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/rejoindre': typeof RejoindreRoute
  '/souscription': typeof SouscriptionRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/admin/abonnements': typeof AdminAbonnementsRoute
  '/admin/boutiques': typeof AdminBoutiquesRoute
  '/admin/facturation': typeof AdminFacturationRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/support': typeof AdminSupportRoute
  '/app/abonnement': typeof AppAbonnementRoute
  '/app/caisse': typeof AppCaisseRoute
  '/app/clients': typeof AppClientsRoute
  '/app/depenses': typeof AppDepensesRoute
  '/app/devis': typeof AppDevisRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/fournisseurs': typeof AppFournisseursRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/produits': typeof AppProduitsRouteWithChildren
  '/app/profil': typeof AppProfilRoute
  '/app/rapports': typeof AppRapportsRoute
  '/app/stock': typeof AppStockRoute
  '/app/support': typeof AppSupportRoute
  '/app/ventes': typeof AppVentesRoute
  '/souscription/confirmation': typeof SouscriptionConfirmationRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/souscription/': typeof SouscriptionIndexRoute
  '/app/produits/$productId': typeof AppProduitsProductIdRoute
  '/app/produits/nouveau': typeof AppProduitsNouveauRoute
  '/app/produits/': typeof AppProduitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/rejoindre': typeof RejoindreRoute
  '/tarifs': typeof TarifsRoute
  '/admin/abonnements': typeof AdminAbonnementsRoute
  '/admin/boutiques': typeof AdminBoutiquesRoute
  '/admin/facturation': typeof AdminFacturationRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/support': typeof AdminSupportRoute
  '/app/abonnement': typeof AppAbonnementRoute
  '/app/caisse': typeof AppCaisseRoute
  '/app/clients': typeof AppClientsRoute
  '/app/depenses': typeof AppDepensesRoute
  '/app/devis': typeof AppDevisRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/fournisseurs': typeof AppFournisseursRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/profil': typeof AppProfilRoute
  '/app/rapports': typeof AppRapportsRoute
  '/app/stock': typeof AppStockRoute
  '/app/support': typeof AppSupportRoute
  '/app/ventes': typeof AppVentesRoute
  '/souscription/confirmation': typeof SouscriptionConfirmationRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/souscription': typeof SouscriptionIndexRoute
  '/app/produits/$productId': typeof AppProduitsProductIdRoute
  '/app/produits/nouveau': typeof AppProduitsNouveauRoute
  '/app/produits': typeof AppProduitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admins': typeof AdminsRoute
  '/app': typeof AppRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/rejoindre': typeof RejoindreRoute
  '/souscription': typeof SouscriptionRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/admin/abonnements': typeof AdminAbonnementsRoute
  '/admin/boutiques': typeof AdminBoutiquesRoute
  '/admin/facturation': typeof AdminFacturationRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/support': typeof AdminSupportRoute
  '/app/abonnement': typeof AppAbonnementRoute
  '/app/caisse': typeof AppCaisseRoute
  '/app/clients': typeof AppClientsRoute
  '/app/depenses': typeof AppDepensesRoute
  '/app/devis': typeof AppDevisRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/fournisseurs': typeof AppFournisseursRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/produits': typeof AppProduitsRouteWithChildren
  '/app/profil': typeof AppProfilRoute
  '/app/rapports': typeof AppRapportsRoute
  '/app/stock': typeof AppStockRoute
  '/app/support': typeof AppSupportRoute
  '/app/ventes': typeof AppVentesRoute
  '/souscription/confirmation': typeof SouscriptionConfirmationRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/souscription/': typeof SouscriptionIndexRoute
  '/app/produits/$productId': typeof AppProduitsProductIdRoute
  '/app/produits/nouveau': typeof AppProduitsNouveauRoute
  '/app/produits/': typeof AppProduitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admins'
    | '/app'
    | '/connexion'
    | '/inscription'
    | '/rejoindre'
    | '/souscription'
    | '/tarifs'
    | '/admin/abonnements'
    | '/admin/boutiques'
    | '/admin/facturation'
    | '/admin/parametres'
    | '/admin/support'
    | '/app/abonnement'
    | '/app/caisse'
    | '/app/clients'
    | '/app/depenses'
    | '/app/devis'
    | '/app/equipe'
    | '/app/fournisseurs'
    | '/app/notifications'
    | '/app/parametres'
    | '/app/produits'
    | '/app/profil'
    | '/app/rapports'
    | '/app/stock'
    | '/app/support'
    | '/app/ventes'
    | '/souscription/confirmation'
    | '/admin/'
    | '/app/'
    | '/souscription/'
    | '/app/produits/$productId'
    | '/app/produits/nouveau'
    | '/app/produits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admins'
    | '/connexion'
    | '/inscription'
    | '/rejoindre'
    | '/tarifs'
    | '/admin/abonnements'
    | '/admin/boutiques'
    | '/admin/facturation'
    | '/admin/parametres'
    | '/admin/support'
    | '/app/abonnement'
    | '/app/caisse'
    | '/app/clients'
    | '/app/depenses'
    | '/app/devis'
    | '/app/equipe'
    | '/app/fournisseurs'
    | '/app/notifications'
    | '/app/parametres'
    | '/app/profil'
    | '/app/rapports'
    | '/app/stock'
    | '/app/support'
    | '/app/ventes'
    | '/souscription/confirmation'
    | '/admin'
    | '/app'
    | '/souscription'
    | '/app/produits/$productId'
    | '/app/produits/nouveau'
    | '/app/produits'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admins'
    | '/app'
    | '/connexion'
    | '/inscription'
    | '/rejoindre'
    | '/souscription'
    | '/tarifs'
    | '/admin/abonnements'
    | '/admin/boutiques'
    | '/admin/facturation'
    | '/admin/parametres'
    | '/admin/support'
    | '/app/abonnement'
    | '/app/caisse'
    | '/app/clients'
    | '/app/depenses'
    | '/app/devis'
    | '/app/equipe'
    | '/app/fournisseurs'
    | '/app/notifications'
    | '/app/parametres'
    | '/app/produits'
    | '/app/profil'
    | '/app/rapports'
    | '/app/stock'
    | '/app/support'
    | '/app/ventes'
    | '/souscription/confirmation'
    | '/admin/'
    | '/app/'
    | '/souscription/'
    | '/app/produits/$productId'
    | '/app/produits/nouveau'
    | '/app/produits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminsRoute: typeof AdminsRoute
  AppRoute: typeof AppRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
  RejoindreRoute: typeof RejoindreRoute
  SouscriptionRoute: typeof SouscriptionRouteWithChildren
  TarifsRoute: typeof TarifsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souscription': {
      id: '/souscription'
      path: '/souscription'
      fullPath: '/souscription'
      preLoaderRoute: typeof SouscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejoindre': {
      id: '/rejoindre'
      path: '/rejoindre'
      fullPath: '/rejoindre'
      preLoaderRoute: typeof RejoindreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souscription/': {
      id: '/souscription/'
      path: '/'
      fullPath: '/souscription/'
      preLoaderRoute: typeof SouscriptionIndexRouteImport
      parentRoute: typeof SouscriptionRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/souscription/confirmation': {
      id: '/souscription/confirmation'
      path: '/confirmation'
      fullPath: '/souscription/confirmation'
      preLoaderRoute: typeof SouscriptionConfirmationRouteImport
      parentRoute: typeof SouscriptionRoute
    }
    '/app/ventes': {
      id: '/app/ventes'
      path: '/ventes'
      fullPath: '/app/ventes'
      preLoaderRoute: typeof AppVentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock': {
      id: '/app/stock'
      path: '/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rapports': {
      id: '/app/rapports'
      path: '/rapports'
      fullPath: '/app/rapports'
      preLoaderRoute: typeof AppRapportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profil': {
      id: '/app/profil'
      path: '/profil'
      fullPath: '/app/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/produits': {
      id: '/app/produits'
      path: '/produits'
      fullPath: '/app/produits'
      preLoaderRoute: typeof AppProduitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parametres': {
      id: '/app/parametres'
      path: '/parametres'
      fullPath: '/app/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fournisseurs': {
      id: '/app/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/app/fournisseurs'
      preLoaderRoute: typeof AppFournisseursRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/devis': {
      id: '/app/devis'
      path: '/devis'
      fullPath: '/app/devis'
      preLoaderRoute: typeof AppDevisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/depenses': {
      id: '/app/depenses'
      path: '/depenses'
      fullPath: '/app/depenses'
      preLoaderRoute: typeof AppDepensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/caisse': {
      id: '/app/caisse'
      path: '/caisse'
      fullPath: '/app/caisse'
      preLoaderRoute: typeof AppCaisseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/abonnement': {
      id: '/app/abonnement'
      path: '/abonnement'
      fullPath: '/app/abonnement'
      preLoaderRoute: typeof AppAbonnementRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturation': {
      id: '/admin/facturation'
      path: '/facturation'
      fullPath: '/admin/facturation'
      preLoaderRoute: typeof AdminFacturationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/boutiques': {
      id: '/admin/boutiques'
      path: '/boutiques'
      fullPath: '/admin/boutiques'
      preLoaderRoute: typeof AdminBoutiquesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abonnements': {
      id: '/admin/abonnements'
      path: '/abonnements'
      fullPath: '/admin/abonnements'
      preLoaderRoute: typeof AdminAbonnementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/produits/': {
      id: '/app/produits/'
      path: '/'
      fullPath: '/app/produits/'
      preLoaderRoute: typeof AppProduitsIndexRouteImport
      parentRoute: typeof AppProduitsRoute
    }
    '/app/produits/nouveau': {
      id: '/app/produits/nouveau'
      path: '/nouveau'
      fullPath: '/app/produits/nouveau'
      preLoaderRoute: typeof AppProduitsNouveauRouteImport
      parentRoute: typeof AppProduitsRoute
    }
    '/app/produits/$productId': {
      id: '/app/produits/$productId'
      path: '/$productId'
      fullPath: '/app/produits/$productId'
      preLoaderRoute: typeof AppProduitsProductIdRouteImport
      parentRoute: typeof AppProduitsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAbonnementsRoute: typeof AdminAbonnementsRoute
  AdminBoutiquesRoute: typeof AdminBoutiquesRoute
  AdminFacturationRoute: typeof AdminFacturationRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbonnementsRoute: AdminAbonnementsRoute,
  AdminBoutiquesRoute: AdminBoutiquesRoute,
  AdminFacturationRoute: AdminFacturationRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppProduitsRouteChildren {
  AppProduitsProductIdRoute: typeof AppProduitsProductIdRoute
  AppProduitsNouveauRoute: typeof AppProduitsNouveauRoute
  AppProduitsIndexRoute: typeof AppProduitsIndexRoute
}

const AppProduitsRouteChildren: AppProduitsRouteChildren = {
  AppProduitsProductIdRoute: AppProduitsProductIdRoute,
  AppProduitsNouveauRoute: AppProduitsNouveauRoute,
  AppProduitsIndexRoute: AppProduitsIndexRoute,
}

const AppProduitsRouteWithChildren = AppProduitsRoute._addFileChildren(
  AppProduitsRouteChildren,
)

interface AppRouteChildren {
  AppAbonnementRoute: typeof AppAbonnementRoute
  AppCaisseRoute: typeof AppCaisseRoute
  AppClientsRoute: typeof AppClientsRoute
  AppDepensesRoute: typeof AppDepensesRoute
  AppDevisRoute: typeof AppDevisRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppFournisseursRoute: typeof AppFournisseursRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppParametresRoute: typeof AppParametresRoute
  AppProduitsRoute: typeof AppProduitsRouteWithChildren
  AppProfilRoute: typeof AppProfilRoute
  AppRapportsRoute: typeof AppRapportsRoute
  AppStockRoute: typeof AppStockRoute
  AppSupportRoute: typeof AppSupportRoute
  AppVentesRoute: typeof AppVentesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAbonnementRoute: AppAbonnementRoute,
  AppCaisseRoute: AppCaisseRoute,
  AppClientsRoute: AppClientsRoute,
  AppDepensesRoute: AppDepensesRoute,
  AppDevisRoute: AppDevisRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppFournisseursRoute: AppFournisseursRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppParametresRoute: AppParametresRoute,
  AppProduitsRoute: AppProduitsRouteWithChildren,
  AppProfilRoute: AppProfilRoute,
  AppRapportsRoute: AppRapportsRoute,
  AppStockRoute: AppStockRoute,
  AppSupportRoute: AppSupportRoute,
  AppVentesRoute: AppVentesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SouscriptionRouteChildren {
  SouscriptionConfirmationRoute: typeof SouscriptionConfirmationRoute
  SouscriptionIndexRoute: typeof SouscriptionIndexRoute
}

const SouscriptionRouteChildren: SouscriptionRouteChildren = {
  SouscriptionConfirmationRoute: SouscriptionConfirmationRoute,
  SouscriptionIndexRoute: SouscriptionIndexRoute,
}

const SouscriptionRouteWithChildren = SouscriptionRoute._addFileChildren(
  SouscriptionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminsRoute: AdminsRoute,
  AppRoute: AppRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
  RejoindreRoute: RejoindreRoute,
  SouscriptionRoute: SouscriptionRouteWithChildren,
  TarifsRoute: TarifsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
