/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SouscriptionRouteImport } from './routes/souscription'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminsRouteImport } from './routes/admins'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SouscriptionIndexRouteImport } from './routes/souscription.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SouscriptionConfirmationRouteImport } from './routes/souscription.confirmation'
import { Route as AppVentesRouteImport } from './routes/app.ventes'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppStockRouteImport } from './routes/app.stock'
import { Route as AppRestoRouteImport } from './routes/app.resto'
import { Route as AppReservationsRouteImport } from './routes/app.reservations'
import { Route as AppRapportsRouteImport } from './routes/app.rapports'
import { Route as AppProfilRouteImport } from './routes/app.profil'
import { Route as AppProduitsRouteImport } from './routes/app.produits'
import { Route as AppParametresRouteImport } from './routes/app.parametres'
import { Route as AppNovaRouteImport } from './routes/app.nova'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppHotelRouteImport } from './routes/app.hotel'
import { Route as AppFournisseursRouteImport } from './routes/app.fournisseurs'
import { Route as AppFneRouteImport } from './routes/app.fne'
import { Route as AppErpRouteImport } from './routes/app.erp'
import { Route as AppEquipeRouteImport } from './routes/app.equipe'
import { Route as AppDevisRouteImport } from './routes/app.devis'
import { Route as AppDepensesRouteImport } from './routes/app.depenses'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppCaisseRouteImport } from './routes/app.caisse'
import { Route as AppAbonnementRouteImport } from './routes/app.abonnement'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminReconciliationRouteImport } from './routes/admin.reconciliation'
import { Route as AdminProfilRouteImport } from './routes/admin.profil'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminImpersonationsRouteImport } from './routes/admin.impersonations'
import { Route as AdminFormulesRouteImport } from './routes/admin.formules'
import { Route as AdminFacturationRouteImport } from './routes/admin.facturation'
import { Route as AdminComptesRouteImport } from './routes/admin.comptes'
import { Route as AdminBoutiquesRouteImport } from './routes/admin.boutiques'
import { Route as AdminAbonnementsRouteImport } from './routes/admin.abonnements'
import { Route as AppVentesIndexRouteImport } from './routes/app.ventes.index'
import { Route as AppRestoIndexRouteImport } from './routes/app.resto.index'
import { Route as AppProduitsIndexRouteImport } from './routes/app.produits.index'
import { Route as AppHotelIndexRouteImport } from './routes/app.hotel.index'
import { Route as AppErpIndexRouteImport } from './routes/app.erp.index'
import { Route as RestoReserverSlugRouteImport } from './routes/resto.reserver.$slug'
import { Route as AppVentesNouvelleRouteImport } from './routes/app.ventes.nouvelle'
import { Route as AppRestoSalleRouteImport } from './routes/app.resto.salle'
import { Route as AppRestoReservationsRouteImport } from './routes/app.resto.reservations'
import { Route as AppRestoRapportsRouteImport } from './routes/app.resto.rapports'
import { Route as AppRestoParametresRouteImport } from './routes/app.resto.parametres'
import { Route as AppRestoMenuRouteImport } from './routes/app.resto.menu'
import { Route as AppRestoFneRouteImport } from './routes/app.resto.fne'
import { Route as AppRestoEquipeRouteImport } from './routes/app.resto.equipe'
import { Route as AppRestoCuisineRouteImport } from './routes/app.resto.cuisine'
import { Route as AppRestoCommandesRouteImport } from './routes/app.resto.commandes'
import { Route as AppProduitsNouveauRouteImport } from './routes/app.produits.nouveau'
import { Route as AppProduitsProductIdRouteImport } from './routes/app.produits.$productId'
import { Route as AppHotelRoomsRouteImport } from './routes/app.hotel.rooms'
import { Route as AppHotelReservationsRouteImport } from './routes/app.hotel.reservations'
import { Route as AppHotelRapportsRouteImport } from './routes/app.hotel.rapports'
import { Route as AppHotelProduitsRouteImport } from './routes/app.hotel.produits'
import { Route as AppHotelPosInterneRouteImport } from './routes/app.hotel.pos-interne'
import { Route as AppHotelParametresRouteImport } from './routes/app.hotel.parametres'
import { Route as AppHotelPaiementsRouteImport } from './routes/app.hotel.paiements'
import { Route as AppHotelMaintenanceRouteImport } from './routes/app.hotel.maintenance'
import { Route as AppHotelHousekeepingRouteImport } from './routes/app.hotel.housekeeping'
import { Route as AppHotelFournisseursRouteImport } from './routes/app.hotel.fournisseurs'
import { Route as AppHotelFneRouteImport } from './routes/app.hotel.fne'
import { Route as AppHotelEquipeRouteImport } from './routes/app.hotel.equipe'
import { Route as AppHotelDepensesRouteImport } from './routes/app.hotel.depenses'
import { Route as AppHotelCorporateRouteImport } from './routes/app.hotel.corporate'
import { Route as AppHotelClientsRouteImport } from './routes/app.hotel.clients'
import { Route as AppErpVentesRouteImport } from './routes/app.erp.ventes'
import { Route as AppErpStockRouteImport } from './routes/app.erp.stock'
import { Route as AppErpRhRouteImport } from './routes/app.erp.rh'
import { Route as AppErpRapportsRouteImport } from './routes/app.erp.rapports'
import { Route as AppErpProduitsRouteImport } from './routes/app.erp.produits'
import { Route as AppErpPosRouteImport } from './routes/app.erp.pos'
import { Route as AppErpParametresRouteImport } from './routes/app.erp.parametres'
import { Route as AppErpFneRouteImport } from './routes/app.erp.fne'
import { Route as AppErpFinanceRouteImport } from './routes/app.erp.finance'
import { Route as AppErpEquipeRouteImport } from './routes/app.erp.equipe'
import { Route as AppErpDocumentsRouteImport } from './routes/app.erp.documents'
import { Route as AppErpComptabiliteRouteImport } from './routes/app.erp.comptabilite'
import { Route as AppErpAchatsRouteImport } from './routes/app.erp.achats'
import { Route as AppHotelProduitsIndexRouteImport } from './routes/app.hotel.produits.index'
import { Route as AppHotelProduitsNouveauRouteImport } from './routes/app.hotel.produits.nouveau'
import { Route as AppHotelProduitsProductIdRouteImport } from './routes/app.hotel.produits.$productId'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SouscriptionRoute = SouscriptionRouteImport.update({
  id: '/souscription',
  path: '/souscription',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRoute = AdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SouscriptionIndexRoute = SouscriptionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SouscriptionRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SouscriptionConfirmationRoute =
  SouscriptionConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => SouscriptionRoute,
  } as any)
const AppVentesRoute = AppVentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppRestoRoute = AppRestoRouteImport.update({
  id: '/resto',
  path: '/resto',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRoute,
} as any)
const AppRapportsRoute = AppRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppProduitsRoute = AppProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AppRoute,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaRoute = AppNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppHotelRoute = AppHotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => AppRoute,
} as any)
const AppFournisseursRoute = AppFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => AppRoute,
} as any)
const AppFneRoute = AppFneRouteImport.update({
  id: '/fne',
  path: '/fne',
  getParentRoute: () => AppRoute,
} as any)
const AppErpRoute = AppErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppDevisRoute = AppDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => AppRoute,
} as any)
const AppDepensesRoute = AppDepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCaisseRoute = AppCaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => AppRoute,
} as any)
const AppAbonnementRoute = AppAbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => AppRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReconciliationRoute = AdminReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfilRoute = AdminProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpersonationsRoute = AdminImpersonationsRouteImport.update({
  id: '/impersonations',
  path: '/impersonations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormulesRoute = AdminFormulesRouteImport.update({
  id: '/formules',
  path: '/formules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturationRoute = AdminFacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComptesRoute = AdminComptesRouteImport.update({
  id: '/comptes',
  path: '/comptes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBoutiquesRoute = AdminBoutiquesRouteImport.update({
  id: '/boutiques',
  path: '/boutiques',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbonnementsRoute = AdminAbonnementsRouteImport.update({
  id: '/abonnements',
  path: '/abonnements',
  getParentRoute: () => AdminRoute,
} as any)
const AppVentesIndexRoute = AppVentesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVentesRoute,
} as any)
const AppRestoIndexRoute = AppRestoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRestoRoute,
} as any)
const AppProduitsIndexRoute = AppProduitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProduitsRoute,
} as any)
const AppHotelIndexRoute = AppHotelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHotelRoute,
} as any)
const AppErpIndexRoute = AppErpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppErpRoute,
} as any)
const RestoReserverSlugRoute = RestoReserverSlugRouteImport.update({
  id: '/resto/reserver/$slug',
  path: '/resto/reserver/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVentesNouvelleRoute = AppVentesNouvelleRouteImport.update({
  id: '/nouvelle',
  path: '/nouvelle',
  getParentRoute: () => AppVentesRoute,
} as any)
const AppRestoSalleRoute = AppRestoSalleRouteImport.update({
  id: '/salle',
  path: '/salle',
  getParentRoute: () => AppRestoRoute,
} as any)
const AppRestoReservationsRoute = AppRestoReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRestoRoute,
} as any)
const AppRestoRapportsRoute = AppRestoRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AppRestoRoute,
} as any)
const AppRestoParametresRoute = AppRestoParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppRestoRoute,
} as any)
const AppRestoMenuRoute = AppRestoMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRestoRoute,
} as any)
const AppRestoFneRoute = AppRestoFneRouteImport.update({
  id: '/fne',
  path: '/fne',
  getParentRoute: () => AppRestoRoute,
} as any)
const AppRestoEquipeRoute = AppRestoEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRestoRoute,
} as any)
const AppRestoCuisineRoute = AppRestoCuisineRouteImport.update({
  id: '/cuisine',
  path: '/cuisine',
  getParentRoute: () => AppRestoRoute,
} as any)
const AppRestoCommandesRoute = AppRestoCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AppRestoRoute,
} as any)
const AppProduitsNouveauRoute = AppProduitsNouveauRouteImport.update({
  id: '/nouveau',
  path: '/nouveau',
  getParentRoute: () => AppProduitsRoute,
} as any)
const AppProduitsProductIdRoute = AppProduitsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AppProduitsRoute,
} as any)
const AppHotelRoomsRoute = AppHotelRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppHotelRoute,
} as any)
const AppHotelReservationsRoute = AppHotelReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppHotelRoute,
} as any)
const AppHotelRapportsRoute = AppHotelRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AppHotelRoute,
} as any)
const AppHotelProduitsRoute = AppHotelProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AppHotelRoute,
} as any)
const AppHotelPosInterneRoute = AppHotelPosInterneRouteImport.update({
  id: '/pos-interne',
  path: '/pos-interne',
  getParentRoute: () => AppHotelRoute,
} as any)
const AppHotelParametresRoute = AppHotelParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppHotelRoute,
} as any)
const AppHotelPaiementsRoute = AppHotelPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AppHotelRoute,
} as any)
const AppHotelMaintenanceRoute = AppHotelMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppHotelRoute,
} as any)
const AppHotelHousekeepingRoute = AppHotelHousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => AppHotelRoute,
} as any)
const AppHotelFournisseursRoute = AppHotelFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => AppHotelRoute,
} as any)
const AppHotelFneRoute = AppHotelFneRouteImport.update({
  id: '/fne',
  path: '/fne',
  getParentRoute: () => AppHotelRoute,
} as any)
const AppHotelEquipeRoute = AppHotelEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppHotelRoute,
} as any)
const AppHotelDepensesRoute = AppHotelDepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => AppHotelRoute,
} as any)
const AppHotelCorporateRoute = AppHotelCorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => AppHotelRoute,
} as any)
const AppHotelClientsRoute = AppHotelClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppHotelRoute,
} as any)
const AppErpVentesRoute = AppErpVentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => AppErpRoute,
} as any)
const AppErpStockRoute = AppErpStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppErpRoute,
} as any)
const AppErpRhRoute = AppErpRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => AppErpRoute,
} as any)
const AppErpRapportsRoute = AppErpRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AppErpRoute,
} as any)
const AppErpProduitsRoute = AppErpProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AppErpRoute,
} as any)
const AppErpPosRoute = AppErpPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppErpRoute,
} as any)
const AppErpParametresRoute = AppErpParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppErpRoute,
} as any)
const AppErpFneRoute = AppErpFneRouteImport.update({
  id: '/fne',
  path: '/fne',
  getParentRoute: () => AppErpRoute,
} as any)
const AppErpFinanceRoute = AppErpFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppErpRoute,
} as any)
const AppErpEquipeRoute = AppErpEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppErpRoute,
} as any)
const AppErpDocumentsRoute = AppErpDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppErpRoute,
} as any)
const AppErpComptabiliteRoute = AppErpComptabiliteRouteImport.update({
  id: '/comptabilite',
  path: '/comptabilite',
  getParentRoute: () => AppErpRoute,
} as any)
const AppErpAchatsRoute = AppErpAchatsRouteImport.update({
  id: '/achats',
  path: '/achats',
  getParentRoute: () => AppErpRoute,
} as any)
const AppHotelProduitsIndexRoute = AppHotelProduitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHotelProduitsRoute,
} as any)
const AppHotelProduitsNouveauRoute = AppHotelProduitsNouveauRouteImport.update({
  id: '/nouveau',
  path: '/nouveau',
  getParentRoute: () => AppHotelProduitsRoute,
} as any)
const AppHotelProduitsProductIdRoute =
  AppHotelProduitsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AppHotelProduitsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admins': typeof AdminsRoute
  '/app': typeof AppRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/souscription': typeof SouscriptionRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/admin/abonnements': typeof AdminAbonnementsRoute
  '/admin/boutiques': typeof AdminBoutiquesRoute
  '/admin/comptes': typeof AdminComptesRoute
  '/admin/facturation': typeof AdminFacturationRoute
  '/admin/formules': typeof AdminFormulesRoute
  '/admin/impersonations': typeof AdminImpersonationsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/profil': typeof AdminProfilRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/support': typeof AdminSupportRoute
  '/app/abonnement': typeof AppAbonnementRoute
  '/app/caisse': typeof AppCaisseRoute
  '/app/clients': typeof AppClientsRoute
  '/app/depenses': typeof AppDepensesRoute
  '/app/devis': typeof AppDevisRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/erp': typeof AppErpRouteWithChildren
  '/app/fne': typeof AppFneRoute
  '/app/fournisseurs': typeof AppFournisseursRoute
  '/app/hotel': typeof AppHotelRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/nova': typeof AppNovaRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/produits': typeof AppProduitsRouteWithChildren
  '/app/profil': typeof AppProfilRoute
  '/app/rapports': typeof AppRapportsRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/resto': typeof AppRestoRouteWithChildren
  '/app/stock': typeof AppStockRoute
  '/app/support': typeof AppSupportRoute
  '/app/ventes': typeof AppVentesRouteWithChildren
  '/souscription/confirmation': typeof SouscriptionConfirmationRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/souscription/': typeof SouscriptionIndexRoute
  '/app/erp/achats': typeof AppErpAchatsRoute
  '/app/erp/comptabilite': typeof AppErpComptabiliteRoute
  '/app/erp/documents': typeof AppErpDocumentsRoute
  '/app/erp/equipe': typeof AppErpEquipeRoute
  '/app/erp/finance': typeof AppErpFinanceRoute
  '/app/erp/fne': typeof AppErpFneRoute
  '/app/erp/parametres': typeof AppErpParametresRoute
  '/app/erp/pos': typeof AppErpPosRoute
  '/app/erp/produits': typeof AppErpProduitsRoute
  '/app/erp/rapports': typeof AppErpRapportsRoute
  '/app/erp/rh': typeof AppErpRhRoute
  '/app/erp/stock': typeof AppErpStockRoute
  '/app/erp/ventes': typeof AppErpVentesRoute
  '/app/hotel/clients': typeof AppHotelClientsRoute
  '/app/hotel/corporate': typeof AppHotelCorporateRoute
  '/app/hotel/depenses': typeof AppHotelDepensesRoute
  '/app/hotel/equipe': typeof AppHotelEquipeRoute
  '/app/hotel/fne': typeof AppHotelFneRoute
  '/app/hotel/fournisseurs': typeof AppHotelFournisseursRoute
  '/app/hotel/housekeeping': typeof AppHotelHousekeepingRoute
  '/app/hotel/maintenance': typeof AppHotelMaintenanceRoute
  '/app/hotel/paiements': typeof AppHotelPaiementsRoute
  '/app/hotel/parametres': typeof AppHotelParametresRoute
  '/app/hotel/pos-interne': typeof AppHotelPosInterneRoute
  '/app/hotel/produits': typeof AppHotelProduitsRouteWithChildren
  '/app/hotel/rapports': typeof AppHotelRapportsRoute
  '/app/hotel/reservations': typeof AppHotelReservationsRoute
  '/app/hotel/rooms': typeof AppHotelRoomsRoute
  '/app/produits/$productId': typeof AppProduitsProductIdRoute
  '/app/produits/nouveau': typeof AppProduitsNouveauRoute
  '/app/resto/commandes': typeof AppRestoCommandesRoute
  '/app/resto/cuisine': typeof AppRestoCuisineRoute
  '/app/resto/equipe': typeof AppRestoEquipeRoute
  '/app/resto/fne': typeof AppRestoFneRoute
  '/app/resto/menu': typeof AppRestoMenuRoute
  '/app/resto/parametres': typeof AppRestoParametresRoute
  '/app/resto/rapports': typeof AppRestoRapportsRoute
  '/app/resto/reservations': typeof AppRestoReservationsRoute
  '/app/resto/salle': typeof AppRestoSalleRoute
  '/app/ventes/nouvelle': typeof AppVentesNouvelleRoute
  '/resto/reserver/$slug': typeof RestoReserverSlugRoute
  '/app/erp/': typeof AppErpIndexRoute
  '/app/hotel/': typeof AppHotelIndexRoute
  '/app/produits/': typeof AppProduitsIndexRoute
  '/app/resto/': typeof AppRestoIndexRoute
  '/app/ventes/': typeof AppVentesIndexRoute
  '/app/hotel/produits/$productId': typeof AppHotelProduitsProductIdRoute
  '/app/hotel/produits/nouveau': typeof AppHotelProduitsNouveauRoute
  '/app/hotel/produits/': typeof AppHotelProduitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/tarifs': typeof TarifsRoute
  '/admin/abonnements': typeof AdminAbonnementsRoute
  '/admin/boutiques': typeof AdminBoutiquesRoute
  '/admin/comptes': typeof AdminComptesRoute
  '/admin/facturation': typeof AdminFacturationRoute
  '/admin/formules': typeof AdminFormulesRoute
  '/admin/impersonations': typeof AdminImpersonationsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/profil': typeof AdminProfilRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/support': typeof AdminSupportRoute
  '/app/abonnement': typeof AppAbonnementRoute
  '/app/caisse': typeof AppCaisseRoute
  '/app/clients': typeof AppClientsRoute
  '/app/depenses': typeof AppDepensesRoute
  '/app/devis': typeof AppDevisRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/fne': typeof AppFneRoute
  '/app/fournisseurs': typeof AppFournisseursRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/nova': typeof AppNovaRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/profil': typeof AppProfilRoute
  '/app/rapports': typeof AppRapportsRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/stock': typeof AppStockRoute
  '/app/support': typeof AppSupportRoute
  '/souscription/confirmation': typeof SouscriptionConfirmationRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/souscription': typeof SouscriptionIndexRoute
  '/app/erp/achats': typeof AppErpAchatsRoute
  '/app/erp/comptabilite': typeof AppErpComptabiliteRoute
  '/app/erp/documents': typeof AppErpDocumentsRoute
  '/app/erp/equipe': typeof AppErpEquipeRoute
  '/app/erp/finance': typeof AppErpFinanceRoute
  '/app/erp/fne': typeof AppErpFneRoute
  '/app/erp/parametres': typeof AppErpParametresRoute
  '/app/erp/pos': typeof AppErpPosRoute
  '/app/erp/produits': typeof AppErpProduitsRoute
  '/app/erp/rapports': typeof AppErpRapportsRoute
  '/app/erp/rh': typeof AppErpRhRoute
  '/app/erp/stock': typeof AppErpStockRoute
  '/app/erp/ventes': typeof AppErpVentesRoute
  '/app/hotel/clients': typeof AppHotelClientsRoute
  '/app/hotel/corporate': typeof AppHotelCorporateRoute
  '/app/hotel/depenses': typeof AppHotelDepensesRoute
  '/app/hotel/equipe': typeof AppHotelEquipeRoute
  '/app/hotel/fne': typeof AppHotelFneRoute
  '/app/hotel/fournisseurs': typeof AppHotelFournisseursRoute
  '/app/hotel/housekeeping': typeof AppHotelHousekeepingRoute
  '/app/hotel/maintenance': typeof AppHotelMaintenanceRoute
  '/app/hotel/paiements': typeof AppHotelPaiementsRoute
  '/app/hotel/parametres': typeof AppHotelParametresRoute
  '/app/hotel/pos-interne': typeof AppHotelPosInterneRoute
  '/app/hotel/rapports': typeof AppHotelRapportsRoute
  '/app/hotel/reservations': typeof AppHotelReservationsRoute
  '/app/hotel/rooms': typeof AppHotelRoomsRoute
  '/app/produits/$productId': typeof AppProduitsProductIdRoute
  '/app/produits/nouveau': typeof AppProduitsNouveauRoute
  '/app/resto/commandes': typeof AppRestoCommandesRoute
  '/app/resto/cuisine': typeof AppRestoCuisineRoute
  '/app/resto/equipe': typeof AppRestoEquipeRoute
  '/app/resto/fne': typeof AppRestoFneRoute
  '/app/resto/menu': typeof AppRestoMenuRoute
  '/app/resto/parametres': typeof AppRestoParametresRoute
  '/app/resto/rapports': typeof AppRestoRapportsRoute
  '/app/resto/reservations': typeof AppRestoReservationsRoute
  '/app/resto/salle': typeof AppRestoSalleRoute
  '/app/ventes/nouvelle': typeof AppVentesNouvelleRoute
  '/resto/reserver/$slug': typeof RestoReserverSlugRoute
  '/app/erp': typeof AppErpIndexRoute
  '/app/hotel': typeof AppHotelIndexRoute
  '/app/produits': typeof AppProduitsIndexRoute
  '/app/resto': typeof AppRestoIndexRoute
  '/app/ventes': typeof AppVentesIndexRoute
  '/app/hotel/produits/$productId': typeof AppHotelProduitsProductIdRoute
  '/app/hotel/produits/nouveau': typeof AppHotelProduitsNouveauRoute
  '/app/hotel/produits': typeof AppHotelProduitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admins': typeof AdminsRoute
  '/app': typeof AppRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/souscription': typeof SouscriptionRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/admin/abonnements': typeof AdminAbonnementsRoute
  '/admin/boutiques': typeof AdminBoutiquesRoute
  '/admin/comptes': typeof AdminComptesRoute
  '/admin/facturation': typeof AdminFacturationRoute
  '/admin/formules': typeof AdminFormulesRoute
  '/admin/impersonations': typeof AdminImpersonationsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/profil': typeof AdminProfilRoute
  '/admin/reconciliation': typeof AdminReconciliationRoute
  '/admin/support': typeof AdminSupportRoute
  '/app/abonnement': typeof AppAbonnementRoute
  '/app/caisse': typeof AppCaisseRoute
  '/app/clients': typeof AppClientsRoute
  '/app/depenses': typeof AppDepensesRoute
  '/app/devis': typeof AppDevisRoute
  '/app/equipe': typeof AppEquipeRoute
  '/app/erp': typeof AppErpRouteWithChildren
  '/app/fne': typeof AppFneRoute
  '/app/fournisseurs': typeof AppFournisseursRoute
  '/app/hotel': typeof AppHotelRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/nova': typeof AppNovaRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/produits': typeof AppProduitsRouteWithChildren
  '/app/profil': typeof AppProfilRoute
  '/app/rapports': typeof AppRapportsRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/resto': typeof AppRestoRouteWithChildren
  '/app/stock': typeof AppStockRoute
  '/app/support': typeof AppSupportRoute
  '/app/ventes': typeof AppVentesRouteWithChildren
  '/souscription/confirmation': typeof SouscriptionConfirmationRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/souscription/': typeof SouscriptionIndexRoute
  '/app/erp/achats': typeof AppErpAchatsRoute
  '/app/erp/comptabilite': typeof AppErpComptabiliteRoute
  '/app/erp/documents': typeof AppErpDocumentsRoute
  '/app/erp/equipe': typeof AppErpEquipeRoute
  '/app/erp/finance': typeof AppErpFinanceRoute
  '/app/erp/fne': typeof AppErpFneRoute
  '/app/erp/parametres': typeof AppErpParametresRoute
  '/app/erp/pos': typeof AppErpPosRoute
  '/app/erp/produits': typeof AppErpProduitsRoute
  '/app/erp/rapports': typeof AppErpRapportsRoute
  '/app/erp/rh': typeof AppErpRhRoute
  '/app/erp/stock': typeof AppErpStockRoute
  '/app/erp/ventes': typeof AppErpVentesRoute
  '/app/hotel/clients': typeof AppHotelClientsRoute
  '/app/hotel/corporate': typeof AppHotelCorporateRoute
  '/app/hotel/depenses': typeof AppHotelDepensesRoute
  '/app/hotel/equipe': typeof AppHotelEquipeRoute
  '/app/hotel/fne': typeof AppHotelFneRoute
  '/app/hotel/fournisseurs': typeof AppHotelFournisseursRoute
  '/app/hotel/housekeeping': typeof AppHotelHousekeepingRoute
  '/app/hotel/maintenance': typeof AppHotelMaintenanceRoute
  '/app/hotel/paiements': typeof AppHotelPaiementsRoute
  '/app/hotel/parametres': typeof AppHotelParametresRoute
  '/app/hotel/pos-interne': typeof AppHotelPosInterneRoute
  '/app/hotel/produits': typeof AppHotelProduitsRouteWithChildren
  '/app/hotel/rapports': typeof AppHotelRapportsRoute
  '/app/hotel/reservations': typeof AppHotelReservationsRoute
  '/app/hotel/rooms': typeof AppHotelRoomsRoute
  '/app/produits/$productId': typeof AppProduitsProductIdRoute
  '/app/produits/nouveau': typeof AppProduitsNouveauRoute
  '/app/resto/commandes': typeof AppRestoCommandesRoute
  '/app/resto/cuisine': typeof AppRestoCuisineRoute
  '/app/resto/equipe': typeof AppRestoEquipeRoute
  '/app/resto/fne': typeof AppRestoFneRoute
  '/app/resto/menu': typeof AppRestoMenuRoute
  '/app/resto/parametres': typeof AppRestoParametresRoute
  '/app/resto/rapports': typeof AppRestoRapportsRoute
  '/app/resto/reservations': typeof AppRestoReservationsRoute
  '/app/resto/salle': typeof AppRestoSalleRoute
  '/app/ventes/nouvelle': typeof AppVentesNouvelleRoute
  '/resto/reserver/$slug': typeof RestoReserverSlugRoute
  '/app/erp/': typeof AppErpIndexRoute
  '/app/hotel/': typeof AppHotelIndexRoute
  '/app/produits/': typeof AppProduitsIndexRoute
  '/app/resto/': typeof AppRestoIndexRoute
  '/app/ventes/': typeof AppVentesIndexRoute
  '/app/hotel/produits/$productId': typeof AppHotelProduitsProductIdRoute
  '/app/hotel/produits/nouveau': typeof AppHotelProduitsNouveauRoute
  '/app/hotel/produits/': typeof AppHotelProduitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admins'
    | '/app'
    | '/connexion'
    | '/inscription'
    | '/souscription'
    | '/tarifs'
    | '/admin/abonnements'
    | '/admin/boutiques'
    | '/admin/comptes'
    | '/admin/facturation'
    | '/admin/formules'
    | '/admin/impersonations'
    | '/admin/parametres'
    | '/admin/profil'
    | '/admin/reconciliation'
    | '/admin/support'
    | '/app/abonnement'
    | '/app/caisse'
    | '/app/clients'
    | '/app/depenses'
    | '/app/devis'
    | '/app/equipe'
    | '/app/erp'
    | '/app/fne'
    | '/app/fournisseurs'
    | '/app/hotel'
    | '/app/notifications'
    | '/app/nova'
    | '/app/parametres'
    | '/app/produits'
    | '/app/profil'
    | '/app/rapports'
    | '/app/reservations'
    | '/app/resto'
    | '/app/stock'
    | '/app/support'
    | '/app/ventes'
    | '/souscription/confirmation'
    | '/admin/'
    | '/app/'
    | '/souscription/'
    | '/app/erp/achats'
    | '/app/erp/comptabilite'
    | '/app/erp/documents'
    | '/app/erp/equipe'
    | '/app/erp/finance'
    | '/app/erp/fne'
    | '/app/erp/parametres'
    | '/app/erp/pos'
    | '/app/erp/produits'
    | '/app/erp/rapports'
    | '/app/erp/rh'
    | '/app/erp/stock'
    | '/app/erp/ventes'
    | '/app/hotel/clients'
    | '/app/hotel/corporate'
    | '/app/hotel/depenses'
    | '/app/hotel/equipe'
    | '/app/hotel/fne'
    | '/app/hotel/fournisseurs'
    | '/app/hotel/housekeeping'
    | '/app/hotel/maintenance'
    | '/app/hotel/paiements'
    | '/app/hotel/parametres'
    | '/app/hotel/pos-interne'
    | '/app/hotel/produits'
    | '/app/hotel/rapports'
    | '/app/hotel/reservations'
    | '/app/hotel/rooms'
    | '/app/produits/$productId'
    | '/app/produits/nouveau'
    | '/app/resto/commandes'
    | '/app/resto/cuisine'
    | '/app/resto/equipe'
    | '/app/resto/fne'
    | '/app/resto/menu'
    | '/app/resto/parametres'
    | '/app/resto/rapports'
    | '/app/resto/reservations'
    | '/app/resto/salle'
    | '/app/ventes/nouvelle'
    | '/resto/reserver/$slug'
    | '/app/erp/'
    | '/app/hotel/'
    | '/app/produits/'
    | '/app/resto/'
    | '/app/ventes/'
    | '/app/hotel/produits/$productId'
    | '/app/hotel/produits/nouveau'
    | '/app/hotel/produits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admins'
    | '/connexion'
    | '/inscription'
    | '/tarifs'
    | '/admin/abonnements'
    | '/admin/boutiques'
    | '/admin/comptes'
    | '/admin/facturation'
    | '/admin/formules'
    | '/admin/impersonations'
    | '/admin/parametres'
    | '/admin/profil'
    | '/admin/reconciliation'
    | '/admin/support'
    | '/app/abonnement'
    | '/app/caisse'
    | '/app/clients'
    | '/app/depenses'
    | '/app/devis'
    | '/app/equipe'
    | '/app/fne'
    | '/app/fournisseurs'
    | '/app/notifications'
    | '/app/nova'
    | '/app/parametres'
    | '/app/profil'
    | '/app/rapports'
    | '/app/reservations'
    | '/app/stock'
    | '/app/support'
    | '/souscription/confirmation'
    | '/admin'
    | '/app'
    | '/souscription'
    | '/app/erp/achats'
    | '/app/erp/comptabilite'
    | '/app/erp/documents'
    | '/app/erp/equipe'
    | '/app/erp/finance'
    | '/app/erp/fne'
    | '/app/erp/parametres'
    | '/app/erp/pos'
    | '/app/erp/produits'
    | '/app/erp/rapports'
    | '/app/erp/rh'
    | '/app/erp/stock'
    | '/app/erp/ventes'
    | '/app/hotel/clients'
    | '/app/hotel/corporate'
    | '/app/hotel/depenses'
    | '/app/hotel/equipe'
    | '/app/hotel/fne'
    | '/app/hotel/fournisseurs'
    | '/app/hotel/housekeeping'
    | '/app/hotel/maintenance'
    | '/app/hotel/paiements'
    | '/app/hotel/parametres'
    | '/app/hotel/pos-interne'
    | '/app/hotel/rapports'
    | '/app/hotel/reservations'
    | '/app/hotel/rooms'
    | '/app/produits/$productId'
    | '/app/produits/nouveau'
    | '/app/resto/commandes'
    | '/app/resto/cuisine'
    | '/app/resto/equipe'
    | '/app/resto/fne'
    | '/app/resto/menu'
    | '/app/resto/parametres'
    | '/app/resto/rapports'
    | '/app/resto/reservations'
    | '/app/resto/salle'
    | '/app/ventes/nouvelle'
    | '/resto/reserver/$slug'
    | '/app/erp'
    | '/app/hotel'
    | '/app/produits'
    | '/app/resto'
    | '/app/ventes'
    | '/app/hotel/produits/$productId'
    | '/app/hotel/produits/nouveau'
    | '/app/hotel/produits'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admins'
    | '/app'
    | '/connexion'
    | '/inscription'
    | '/souscription'
    | '/tarifs'
    | '/admin/abonnements'
    | '/admin/boutiques'
    | '/admin/comptes'
    | '/admin/facturation'
    | '/admin/formules'
    | '/admin/impersonations'
    | '/admin/parametres'
    | '/admin/profil'
    | '/admin/reconciliation'
    | '/admin/support'
    | '/app/abonnement'
    | '/app/caisse'
    | '/app/clients'
    | '/app/depenses'
    | '/app/devis'
    | '/app/equipe'
    | '/app/erp'
    | '/app/fne'
    | '/app/fournisseurs'
    | '/app/hotel'
    | '/app/notifications'
    | '/app/nova'
    | '/app/parametres'
    | '/app/produits'
    | '/app/profil'
    | '/app/rapports'
    | '/app/reservations'
    | '/app/resto'
    | '/app/stock'
    | '/app/support'
    | '/app/ventes'
    | '/souscription/confirmation'
    | '/admin/'
    | '/app/'
    | '/souscription/'
    | '/app/erp/achats'
    | '/app/erp/comptabilite'
    | '/app/erp/documents'
    | '/app/erp/equipe'
    | '/app/erp/finance'
    | '/app/erp/fne'
    | '/app/erp/parametres'
    | '/app/erp/pos'
    | '/app/erp/produits'
    | '/app/erp/rapports'
    | '/app/erp/rh'
    | '/app/erp/stock'
    | '/app/erp/ventes'
    | '/app/hotel/clients'
    | '/app/hotel/corporate'
    | '/app/hotel/depenses'
    | '/app/hotel/equipe'
    | '/app/hotel/fne'
    | '/app/hotel/fournisseurs'
    | '/app/hotel/housekeeping'
    | '/app/hotel/maintenance'
    | '/app/hotel/paiements'
    | '/app/hotel/parametres'
    | '/app/hotel/pos-interne'
    | '/app/hotel/produits'
    | '/app/hotel/rapports'
    | '/app/hotel/reservations'
    | '/app/hotel/rooms'
    | '/app/produits/$productId'
    | '/app/produits/nouveau'
    | '/app/resto/commandes'
    | '/app/resto/cuisine'
    | '/app/resto/equipe'
    | '/app/resto/fne'
    | '/app/resto/menu'
    | '/app/resto/parametres'
    | '/app/resto/rapports'
    | '/app/resto/reservations'
    | '/app/resto/salle'
    | '/app/ventes/nouvelle'
    | '/resto/reserver/$slug'
    | '/app/erp/'
    | '/app/hotel/'
    | '/app/produits/'
    | '/app/resto/'
    | '/app/ventes/'
    | '/app/hotel/produits/$productId'
    | '/app/hotel/produits/nouveau'
    | '/app/hotel/produits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminsRoute: typeof AdminsRoute
  AppRoute: typeof AppRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
  SouscriptionRoute: typeof SouscriptionRouteWithChildren
  TarifsRoute: typeof TarifsRoute
  RestoReserverSlugRoute: typeof RestoReserverSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souscription': {
      id: '/souscription'
      path: '/souscription'
      fullPath: '/souscription'
      preLoaderRoute: typeof SouscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souscription/': {
      id: '/souscription/'
      path: '/'
      fullPath: '/souscription/'
      preLoaderRoute: typeof SouscriptionIndexRouteImport
      parentRoute: typeof SouscriptionRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/souscription/confirmation': {
      id: '/souscription/confirmation'
      path: '/confirmation'
      fullPath: '/souscription/confirmation'
      preLoaderRoute: typeof SouscriptionConfirmationRouteImport
      parentRoute: typeof SouscriptionRoute
    }
    '/app/ventes': {
      id: '/app/ventes'
      path: '/ventes'
      fullPath: '/app/ventes'
      preLoaderRoute: typeof AppVentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock': {
      id: '/app/stock'
      path: '/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resto': {
      id: '/app/resto'
      path: '/resto'
      fullPath: '/app/resto'
      preLoaderRoute: typeof AppRestoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reservations': {
      id: '/app/reservations'
      path: '/reservations'
      fullPath: '/app/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rapports': {
      id: '/app/rapports'
      path: '/rapports'
      fullPath: '/app/rapports'
      preLoaderRoute: typeof AppRapportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profil': {
      id: '/app/profil'
      path: '/profil'
      fullPath: '/app/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/produits': {
      id: '/app/produits'
      path: '/produits'
      fullPath: '/app/produits'
      preLoaderRoute: typeof AppProduitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/parametres': {
      id: '/app/parametres'
      path: '/parametres'
      fullPath: '/app/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nova': {
      id: '/app/nova'
      path: '/nova'
      fullPath: '/app/nova'
      preLoaderRoute: typeof AppNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hotel': {
      id: '/app/hotel'
      path: '/hotel'
      fullPath: '/app/hotel'
      preLoaderRoute: typeof AppHotelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fournisseurs': {
      id: '/app/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/app/fournisseurs'
      preLoaderRoute: typeof AppFournisseursRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fne': {
      id: '/app/fne'
      path: '/fne'
      fullPath: '/app/fne'
      preLoaderRoute: typeof AppFneRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/erp': {
      id: '/app/erp'
      path: '/erp'
      fullPath: '/app/erp'
      preLoaderRoute: typeof AppErpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/devis': {
      id: '/app/devis'
      path: '/devis'
      fullPath: '/app/devis'
      preLoaderRoute: typeof AppDevisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/depenses': {
      id: '/app/depenses'
      path: '/depenses'
      fullPath: '/app/depenses'
      preLoaderRoute: typeof AppDepensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/caisse': {
      id: '/app/caisse'
      path: '/caisse'
      fullPath: '/app/caisse'
      preLoaderRoute: typeof AppCaisseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/abonnement': {
      id: '/app/abonnement'
      path: '/abonnement'
      fullPath: '/app/abonnement'
      preLoaderRoute: typeof AppAbonnementRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reconciliation': {
      id: '/admin/reconciliation'
      path: '/reconciliation'
      fullPath: '/admin/reconciliation'
      preLoaderRoute: typeof AdminReconciliationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profil': {
      id: '/admin/profil'
      path: '/profil'
      fullPath: '/admin/profil'
      preLoaderRoute: typeof AdminProfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impersonations': {
      id: '/admin/impersonations'
      path: '/impersonations'
      fullPath: '/admin/impersonations'
      preLoaderRoute: typeof AdminImpersonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/formules': {
      id: '/admin/formules'
      path: '/formules'
      fullPath: '/admin/formules'
      preLoaderRoute: typeof AdminFormulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturation': {
      id: '/admin/facturation'
      path: '/facturation'
      fullPath: '/admin/facturation'
      preLoaderRoute: typeof AdminFacturationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comptes': {
      id: '/admin/comptes'
      path: '/comptes'
      fullPath: '/admin/comptes'
      preLoaderRoute: typeof AdminComptesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/boutiques': {
      id: '/admin/boutiques'
      path: '/boutiques'
      fullPath: '/admin/boutiques'
      preLoaderRoute: typeof AdminBoutiquesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abonnements': {
      id: '/admin/abonnements'
      path: '/abonnements'
      fullPath: '/admin/abonnements'
      preLoaderRoute: typeof AdminAbonnementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/ventes/': {
      id: '/app/ventes/'
      path: '/'
      fullPath: '/app/ventes/'
      preLoaderRoute: typeof AppVentesIndexRouteImport
      parentRoute: typeof AppVentesRoute
    }
    '/app/resto/': {
      id: '/app/resto/'
      path: '/'
      fullPath: '/app/resto/'
      preLoaderRoute: typeof AppRestoIndexRouteImport
      parentRoute: typeof AppRestoRoute
    }
    '/app/produits/': {
      id: '/app/produits/'
      path: '/'
      fullPath: '/app/produits/'
      preLoaderRoute: typeof AppProduitsIndexRouteImport
      parentRoute: typeof AppProduitsRoute
    }
    '/app/hotel/': {
      id: '/app/hotel/'
      path: '/'
      fullPath: '/app/hotel/'
      preLoaderRoute: typeof AppHotelIndexRouteImport
      parentRoute: typeof AppHotelRoute
    }
    '/app/erp/': {
      id: '/app/erp/'
      path: '/'
      fullPath: '/app/erp/'
      preLoaderRoute: typeof AppErpIndexRouteImport
      parentRoute: typeof AppErpRoute
    }
    '/resto/reserver/$slug': {
      id: '/resto/reserver/$slug'
      path: '/resto/reserver/$slug'
      fullPath: '/resto/reserver/$slug'
      preLoaderRoute: typeof RestoReserverSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/ventes/nouvelle': {
      id: '/app/ventes/nouvelle'
      path: '/nouvelle'
      fullPath: '/app/ventes/nouvelle'
      preLoaderRoute: typeof AppVentesNouvelleRouteImport
      parentRoute: typeof AppVentesRoute
    }
    '/app/resto/salle': {
      id: '/app/resto/salle'
      path: '/salle'
      fullPath: '/app/resto/salle'
      preLoaderRoute: typeof AppRestoSalleRouteImport
      parentRoute: typeof AppRestoRoute
    }
    '/app/resto/reservations': {
      id: '/app/resto/reservations'
      path: '/reservations'
      fullPath: '/app/resto/reservations'
      preLoaderRoute: typeof AppRestoReservationsRouteImport
      parentRoute: typeof AppRestoRoute
    }
    '/app/resto/rapports': {
      id: '/app/resto/rapports'
      path: '/rapports'
      fullPath: '/app/resto/rapports'
      preLoaderRoute: typeof AppRestoRapportsRouteImport
      parentRoute: typeof AppRestoRoute
    }
    '/app/resto/parametres': {
      id: '/app/resto/parametres'
      path: '/parametres'
      fullPath: '/app/resto/parametres'
      preLoaderRoute: typeof AppRestoParametresRouteImport
      parentRoute: typeof AppRestoRoute
    }
    '/app/resto/menu': {
      id: '/app/resto/menu'
      path: '/menu'
      fullPath: '/app/resto/menu'
      preLoaderRoute: typeof AppRestoMenuRouteImport
      parentRoute: typeof AppRestoRoute
    }
    '/app/resto/fne': {
      id: '/app/resto/fne'
      path: '/fne'
      fullPath: '/app/resto/fne'
      preLoaderRoute: typeof AppRestoFneRouteImport
      parentRoute: typeof AppRestoRoute
    }
    '/app/resto/equipe': {
      id: '/app/resto/equipe'
      path: '/equipe'
      fullPath: '/app/resto/equipe'
      preLoaderRoute: typeof AppRestoEquipeRouteImport
      parentRoute: typeof AppRestoRoute
    }
    '/app/resto/cuisine': {
      id: '/app/resto/cuisine'
      path: '/cuisine'
      fullPath: '/app/resto/cuisine'
      preLoaderRoute: typeof AppRestoCuisineRouteImport
      parentRoute: typeof AppRestoRoute
    }
    '/app/resto/commandes': {
      id: '/app/resto/commandes'
      path: '/commandes'
      fullPath: '/app/resto/commandes'
      preLoaderRoute: typeof AppRestoCommandesRouteImport
      parentRoute: typeof AppRestoRoute
    }
    '/app/produits/nouveau': {
      id: '/app/produits/nouveau'
      path: '/nouveau'
      fullPath: '/app/produits/nouveau'
      preLoaderRoute: typeof AppProduitsNouveauRouteImport
      parentRoute: typeof AppProduitsRoute
    }
    '/app/produits/$productId': {
      id: '/app/produits/$productId'
      path: '/$productId'
      fullPath: '/app/produits/$productId'
      preLoaderRoute: typeof AppProduitsProductIdRouteImport
      parentRoute: typeof AppProduitsRoute
    }
    '/app/hotel/rooms': {
      id: '/app/hotel/rooms'
      path: '/rooms'
      fullPath: '/app/hotel/rooms'
      preLoaderRoute: typeof AppHotelRoomsRouteImport
      parentRoute: typeof AppHotelRoute
    }
    '/app/hotel/reservations': {
      id: '/app/hotel/reservations'
      path: '/reservations'
      fullPath: '/app/hotel/reservations'
      preLoaderRoute: typeof AppHotelReservationsRouteImport
      parentRoute: typeof AppHotelRoute
    }
    '/app/hotel/rapports': {
      id: '/app/hotel/rapports'
      path: '/rapports'
      fullPath: '/app/hotel/rapports'
      preLoaderRoute: typeof AppHotelRapportsRouteImport
      parentRoute: typeof AppHotelRoute
    }
    '/app/hotel/produits': {
      id: '/app/hotel/produits'
      path: '/produits'
      fullPath: '/app/hotel/produits'
      preLoaderRoute: typeof AppHotelProduitsRouteImport
      parentRoute: typeof AppHotelRoute
    }
    '/app/hotel/pos-interne': {
      id: '/app/hotel/pos-interne'
      path: '/pos-interne'
      fullPath: '/app/hotel/pos-interne'
      preLoaderRoute: typeof AppHotelPosInterneRouteImport
      parentRoute: typeof AppHotelRoute
    }
    '/app/hotel/parametres': {
      id: '/app/hotel/parametres'
      path: '/parametres'
      fullPath: '/app/hotel/parametres'
      preLoaderRoute: typeof AppHotelParametresRouteImport
      parentRoute: typeof AppHotelRoute
    }
    '/app/hotel/paiements': {
      id: '/app/hotel/paiements'
      path: '/paiements'
      fullPath: '/app/hotel/paiements'
      preLoaderRoute: typeof AppHotelPaiementsRouteImport
      parentRoute: typeof AppHotelRoute
    }
    '/app/hotel/maintenance': {
      id: '/app/hotel/maintenance'
      path: '/maintenance'
      fullPath: '/app/hotel/maintenance'
      preLoaderRoute: typeof AppHotelMaintenanceRouteImport
      parentRoute: typeof AppHotelRoute
    }
    '/app/hotel/housekeeping': {
      id: '/app/hotel/housekeeping'
      path: '/housekeeping'
      fullPath: '/app/hotel/housekeeping'
      preLoaderRoute: typeof AppHotelHousekeepingRouteImport
      parentRoute: typeof AppHotelRoute
    }
    '/app/hotel/fournisseurs': {
      id: '/app/hotel/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/app/hotel/fournisseurs'
      preLoaderRoute: typeof AppHotelFournisseursRouteImport
      parentRoute: typeof AppHotelRoute
    }
    '/app/hotel/fne': {
      id: '/app/hotel/fne'
      path: '/fne'
      fullPath: '/app/hotel/fne'
      preLoaderRoute: typeof AppHotelFneRouteImport
      parentRoute: typeof AppHotelRoute
    }
    '/app/hotel/equipe': {
      id: '/app/hotel/equipe'
      path: '/equipe'
      fullPath: '/app/hotel/equipe'
      preLoaderRoute: typeof AppHotelEquipeRouteImport
      parentRoute: typeof AppHotelRoute
    }
    '/app/hotel/depenses': {
      id: '/app/hotel/depenses'
      path: '/depenses'
      fullPath: '/app/hotel/depenses'
      preLoaderRoute: typeof AppHotelDepensesRouteImport
      parentRoute: typeof AppHotelRoute
    }
    '/app/hotel/corporate': {
      id: '/app/hotel/corporate'
      path: '/corporate'
      fullPath: '/app/hotel/corporate'
      preLoaderRoute: typeof AppHotelCorporateRouteImport
      parentRoute: typeof AppHotelRoute
    }
    '/app/hotel/clients': {
      id: '/app/hotel/clients'
      path: '/clients'
      fullPath: '/app/hotel/clients'
      preLoaderRoute: typeof AppHotelClientsRouteImport
      parentRoute: typeof AppHotelRoute
    }
    '/app/erp/ventes': {
      id: '/app/erp/ventes'
      path: '/ventes'
      fullPath: '/app/erp/ventes'
      preLoaderRoute: typeof AppErpVentesRouteImport
      parentRoute: typeof AppErpRoute
    }
    '/app/erp/stock': {
      id: '/app/erp/stock'
      path: '/stock'
      fullPath: '/app/erp/stock'
      preLoaderRoute: typeof AppErpStockRouteImport
      parentRoute: typeof AppErpRoute
    }
    '/app/erp/rh': {
      id: '/app/erp/rh'
      path: '/rh'
      fullPath: '/app/erp/rh'
      preLoaderRoute: typeof AppErpRhRouteImport
      parentRoute: typeof AppErpRoute
    }
    '/app/erp/rapports': {
      id: '/app/erp/rapports'
      path: '/rapports'
      fullPath: '/app/erp/rapports'
      preLoaderRoute: typeof AppErpRapportsRouteImport
      parentRoute: typeof AppErpRoute
    }
    '/app/erp/produits': {
      id: '/app/erp/produits'
      path: '/produits'
      fullPath: '/app/erp/produits'
      preLoaderRoute: typeof AppErpProduitsRouteImport
      parentRoute: typeof AppErpRoute
    }
    '/app/erp/pos': {
      id: '/app/erp/pos'
      path: '/pos'
      fullPath: '/app/erp/pos'
      preLoaderRoute: typeof AppErpPosRouteImport
      parentRoute: typeof AppErpRoute
    }
    '/app/erp/parametres': {
      id: '/app/erp/parametres'
      path: '/parametres'
      fullPath: '/app/erp/parametres'
      preLoaderRoute: typeof AppErpParametresRouteImport
      parentRoute: typeof AppErpRoute
    }
    '/app/erp/fne': {
      id: '/app/erp/fne'
      path: '/fne'
      fullPath: '/app/erp/fne'
      preLoaderRoute: typeof AppErpFneRouteImport
      parentRoute: typeof AppErpRoute
    }
    '/app/erp/finance': {
      id: '/app/erp/finance'
      path: '/finance'
      fullPath: '/app/erp/finance'
      preLoaderRoute: typeof AppErpFinanceRouteImport
      parentRoute: typeof AppErpRoute
    }
    '/app/erp/equipe': {
      id: '/app/erp/equipe'
      path: '/equipe'
      fullPath: '/app/erp/equipe'
      preLoaderRoute: typeof AppErpEquipeRouteImport
      parentRoute: typeof AppErpRoute
    }
    '/app/erp/documents': {
      id: '/app/erp/documents'
      path: '/documents'
      fullPath: '/app/erp/documents'
      preLoaderRoute: typeof AppErpDocumentsRouteImport
      parentRoute: typeof AppErpRoute
    }
    '/app/erp/comptabilite': {
      id: '/app/erp/comptabilite'
      path: '/comptabilite'
      fullPath: '/app/erp/comptabilite'
      preLoaderRoute: typeof AppErpComptabiliteRouteImport
      parentRoute: typeof AppErpRoute
    }
    '/app/erp/achats': {
      id: '/app/erp/achats'
      path: '/achats'
      fullPath: '/app/erp/achats'
      preLoaderRoute: typeof AppErpAchatsRouteImport
      parentRoute: typeof AppErpRoute
    }
    '/app/hotel/produits/': {
      id: '/app/hotel/produits/'
      path: '/'
      fullPath: '/app/hotel/produits/'
      preLoaderRoute: typeof AppHotelProduitsIndexRouteImport
      parentRoute: typeof AppHotelProduitsRoute
    }
    '/app/hotel/produits/nouveau': {
      id: '/app/hotel/produits/nouveau'
      path: '/nouveau'
      fullPath: '/app/hotel/produits/nouveau'
      preLoaderRoute: typeof AppHotelProduitsNouveauRouteImport
      parentRoute: typeof AppHotelProduitsRoute
    }
    '/app/hotel/produits/$productId': {
      id: '/app/hotel/produits/$productId'
      path: '/$productId'
      fullPath: '/app/hotel/produits/$productId'
      preLoaderRoute: typeof AppHotelProduitsProductIdRouteImport
      parentRoute: typeof AppHotelProduitsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAbonnementsRoute: typeof AdminAbonnementsRoute
  AdminBoutiquesRoute: typeof AdminBoutiquesRoute
  AdminComptesRoute: typeof AdminComptesRoute
  AdminFacturationRoute: typeof AdminFacturationRoute
  AdminFormulesRoute: typeof AdminFormulesRoute
  AdminImpersonationsRoute: typeof AdminImpersonationsRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminProfilRoute: typeof AdminProfilRoute
  AdminReconciliationRoute: typeof AdminReconciliationRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbonnementsRoute: AdminAbonnementsRoute,
  AdminBoutiquesRoute: AdminBoutiquesRoute,
  AdminComptesRoute: AdminComptesRoute,
  AdminFacturationRoute: AdminFacturationRoute,
  AdminFormulesRoute: AdminFormulesRoute,
  AdminImpersonationsRoute: AdminImpersonationsRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminProfilRoute: AdminProfilRoute,
  AdminReconciliationRoute: AdminReconciliationRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppErpRouteChildren {
  AppErpAchatsRoute: typeof AppErpAchatsRoute
  AppErpComptabiliteRoute: typeof AppErpComptabiliteRoute
  AppErpDocumentsRoute: typeof AppErpDocumentsRoute
  AppErpEquipeRoute: typeof AppErpEquipeRoute
  AppErpFinanceRoute: typeof AppErpFinanceRoute
  AppErpFneRoute: typeof AppErpFneRoute
  AppErpParametresRoute: typeof AppErpParametresRoute
  AppErpPosRoute: typeof AppErpPosRoute
  AppErpProduitsRoute: typeof AppErpProduitsRoute
  AppErpRapportsRoute: typeof AppErpRapportsRoute
  AppErpRhRoute: typeof AppErpRhRoute
  AppErpStockRoute: typeof AppErpStockRoute
  AppErpVentesRoute: typeof AppErpVentesRoute
  AppErpIndexRoute: typeof AppErpIndexRoute
}

const AppErpRouteChildren: AppErpRouteChildren = {
  AppErpAchatsRoute: AppErpAchatsRoute,
  AppErpComptabiliteRoute: AppErpComptabiliteRoute,
  AppErpDocumentsRoute: AppErpDocumentsRoute,
  AppErpEquipeRoute: AppErpEquipeRoute,
  AppErpFinanceRoute: AppErpFinanceRoute,
  AppErpFneRoute: AppErpFneRoute,
  AppErpParametresRoute: AppErpParametresRoute,
  AppErpPosRoute: AppErpPosRoute,
  AppErpProduitsRoute: AppErpProduitsRoute,
  AppErpRapportsRoute: AppErpRapportsRoute,
  AppErpRhRoute: AppErpRhRoute,
  AppErpStockRoute: AppErpStockRoute,
  AppErpVentesRoute: AppErpVentesRoute,
  AppErpIndexRoute: AppErpIndexRoute,
}

const AppErpRouteWithChildren =
  AppErpRoute._addFileChildren(AppErpRouteChildren)

interface AppHotelProduitsRouteChildren {
  AppHotelProduitsProductIdRoute: typeof AppHotelProduitsProductIdRoute
  AppHotelProduitsNouveauRoute: typeof AppHotelProduitsNouveauRoute
  AppHotelProduitsIndexRoute: typeof AppHotelProduitsIndexRoute
}

const AppHotelProduitsRouteChildren: AppHotelProduitsRouteChildren = {
  AppHotelProduitsProductIdRoute: AppHotelProduitsProductIdRoute,
  AppHotelProduitsNouveauRoute: AppHotelProduitsNouveauRoute,
  AppHotelProduitsIndexRoute: AppHotelProduitsIndexRoute,
}

const AppHotelProduitsRouteWithChildren =
  AppHotelProduitsRoute._addFileChildren(AppHotelProduitsRouteChildren)

interface AppHotelRouteChildren {
  AppHotelClientsRoute: typeof AppHotelClientsRoute
  AppHotelCorporateRoute: typeof AppHotelCorporateRoute
  AppHotelDepensesRoute: typeof AppHotelDepensesRoute
  AppHotelEquipeRoute: typeof AppHotelEquipeRoute
  AppHotelFneRoute: typeof AppHotelFneRoute
  AppHotelFournisseursRoute: typeof AppHotelFournisseursRoute
  AppHotelHousekeepingRoute: typeof AppHotelHousekeepingRoute
  AppHotelMaintenanceRoute: typeof AppHotelMaintenanceRoute
  AppHotelPaiementsRoute: typeof AppHotelPaiementsRoute
  AppHotelParametresRoute: typeof AppHotelParametresRoute
  AppHotelPosInterneRoute: typeof AppHotelPosInterneRoute
  AppHotelProduitsRoute: typeof AppHotelProduitsRouteWithChildren
  AppHotelRapportsRoute: typeof AppHotelRapportsRoute
  AppHotelReservationsRoute: typeof AppHotelReservationsRoute
  AppHotelRoomsRoute: typeof AppHotelRoomsRoute
  AppHotelIndexRoute: typeof AppHotelIndexRoute
}

const AppHotelRouteChildren: AppHotelRouteChildren = {
  AppHotelClientsRoute: AppHotelClientsRoute,
  AppHotelCorporateRoute: AppHotelCorporateRoute,
  AppHotelDepensesRoute: AppHotelDepensesRoute,
  AppHotelEquipeRoute: AppHotelEquipeRoute,
  AppHotelFneRoute: AppHotelFneRoute,
  AppHotelFournisseursRoute: AppHotelFournisseursRoute,
  AppHotelHousekeepingRoute: AppHotelHousekeepingRoute,
  AppHotelMaintenanceRoute: AppHotelMaintenanceRoute,
  AppHotelPaiementsRoute: AppHotelPaiementsRoute,
  AppHotelParametresRoute: AppHotelParametresRoute,
  AppHotelPosInterneRoute: AppHotelPosInterneRoute,
  AppHotelProduitsRoute: AppHotelProduitsRouteWithChildren,
  AppHotelRapportsRoute: AppHotelRapportsRoute,
  AppHotelReservationsRoute: AppHotelReservationsRoute,
  AppHotelRoomsRoute: AppHotelRoomsRoute,
  AppHotelIndexRoute: AppHotelIndexRoute,
}

const AppHotelRouteWithChildren = AppHotelRoute._addFileChildren(
  AppHotelRouteChildren,
)

interface AppProduitsRouteChildren {
  AppProduitsProductIdRoute: typeof AppProduitsProductIdRoute
  AppProduitsNouveauRoute: typeof AppProduitsNouveauRoute
  AppProduitsIndexRoute: typeof AppProduitsIndexRoute
}

const AppProduitsRouteChildren: AppProduitsRouteChildren = {
  AppProduitsProductIdRoute: AppProduitsProductIdRoute,
  AppProduitsNouveauRoute: AppProduitsNouveauRoute,
  AppProduitsIndexRoute: AppProduitsIndexRoute,
}

const AppProduitsRouteWithChildren = AppProduitsRoute._addFileChildren(
  AppProduitsRouteChildren,
)

interface AppRestoRouteChildren {
  AppRestoCommandesRoute: typeof AppRestoCommandesRoute
  AppRestoCuisineRoute: typeof AppRestoCuisineRoute
  AppRestoEquipeRoute: typeof AppRestoEquipeRoute
  AppRestoFneRoute: typeof AppRestoFneRoute
  AppRestoMenuRoute: typeof AppRestoMenuRoute
  AppRestoParametresRoute: typeof AppRestoParametresRoute
  AppRestoRapportsRoute: typeof AppRestoRapportsRoute
  AppRestoReservationsRoute: typeof AppRestoReservationsRoute
  AppRestoSalleRoute: typeof AppRestoSalleRoute
  AppRestoIndexRoute: typeof AppRestoIndexRoute
}

const AppRestoRouteChildren: AppRestoRouteChildren = {
  AppRestoCommandesRoute: AppRestoCommandesRoute,
  AppRestoCuisineRoute: AppRestoCuisineRoute,
  AppRestoEquipeRoute: AppRestoEquipeRoute,
  AppRestoFneRoute: AppRestoFneRoute,
  AppRestoMenuRoute: AppRestoMenuRoute,
  AppRestoParametresRoute: AppRestoParametresRoute,
  AppRestoRapportsRoute: AppRestoRapportsRoute,
  AppRestoReservationsRoute: AppRestoReservationsRoute,
  AppRestoSalleRoute: AppRestoSalleRoute,
  AppRestoIndexRoute: AppRestoIndexRoute,
}

const AppRestoRouteWithChildren = AppRestoRoute._addFileChildren(
  AppRestoRouteChildren,
)

interface AppVentesRouteChildren {
  AppVentesNouvelleRoute: typeof AppVentesNouvelleRoute
  AppVentesIndexRoute: typeof AppVentesIndexRoute
}

const AppVentesRouteChildren: AppVentesRouteChildren = {
  AppVentesNouvelleRoute: AppVentesNouvelleRoute,
  AppVentesIndexRoute: AppVentesIndexRoute,
}

const AppVentesRouteWithChildren = AppVentesRoute._addFileChildren(
  AppVentesRouteChildren,
)

interface AppRouteChildren {
  AppAbonnementRoute: typeof AppAbonnementRoute
  AppCaisseRoute: typeof AppCaisseRoute
  AppClientsRoute: typeof AppClientsRoute
  AppDepensesRoute: typeof AppDepensesRoute
  AppDevisRoute: typeof AppDevisRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppErpRoute: typeof AppErpRouteWithChildren
  AppFneRoute: typeof AppFneRoute
  AppFournisseursRoute: typeof AppFournisseursRoute
  AppHotelRoute: typeof AppHotelRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppNovaRoute: typeof AppNovaRoute
  AppParametresRoute: typeof AppParametresRoute
  AppProduitsRoute: typeof AppProduitsRouteWithChildren
  AppProfilRoute: typeof AppProfilRoute
  AppRapportsRoute: typeof AppRapportsRoute
  AppReservationsRoute: typeof AppReservationsRoute
  AppRestoRoute: typeof AppRestoRouteWithChildren
  AppStockRoute: typeof AppStockRoute
  AppSupportRoute: typeof AppSupportRoute
  AppVentesRoute: typeof AppVentesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAbonnementRoute: AppAbonnementRoute,
  AppCaisseRoute: AppCaisseRoute,
  AppClientsRoute: AppClientsRoute,
  AppDepensesRoute: AppDepensesRoute,
  AppDevisRoute: AppDevisRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppErpRoute: AppErpRouteWithChildren,
  AppFneRoute: AppFneRoute,
  AppFournisseursRoute: AppFournisseursRoute,
  AppHotelRoute: AppHotelRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppNovaRoute: AppNovaRoute,
  AppParametresRoute: AppParametresRoute,
  AppProduitsRoute: AppProduitsRouteWithChildren,
  AppProfilRoute: AppProfilRoute,
  AppRapportsRoute: AppRapportsRoute,
  AppReservationsRoute: AppReservationsRoute,
  AppRestoRoute: AppRestoRouteWithChildren,
  AppStockRoute: AppStockRoute,
  AppSupportRoute: AppSupportRoute,
  AppVentesRoute: AppVentesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SouscriptionRouteChildren {
  SouscriptionConfirmationRoute: typeof SouscriptionConfirmationRoute
  SouscriptionIndexRoute: typeof SouscriptionIndexRoute
}

const SouscriptionRouteChildren: SouscriptionRouteChildren = {
  SouscriptionConfirmationRoute: SouscriptionConfirmationRoute,
  SouscriptionIndexRoute: SouscriptionIndexRoute,
}

const SouscriptionRouteWithChildren = SouscriptionRoute._addFileChildren(
  SouscriptionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminsRoute: AdminsRoute,
  AppRoute: AppRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
  SouscriptionRoute: SouscriptionRouteWithChildren,
  TarifsRoute: TarifsRoute,
  RestoReserverSlugRoute: RestoReserverSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
